(($) ->
  $(document).ready ->

    ChangeUrl = (page, url) ->
      if typeof history.pushState != 'undefined'
        obj =
          Page: page
          Url: url
        history.pushState obj, obj.Page, obj.Url
      else
        alert 'Browser does not support HTML5.'
      return

    $('.calendar').on 'click', 'a.calendar-control', (event) ->
      href = $(this).attr('href')
      $.get href, (data) ->
        $calendar = $('table.calendar', data)
        $('table.calendar').html $calendar
        return
      ChangeUrl document.title, href
      event.preventDefault()
      false
    return
    
  return
) jQuery

# ---
# generated by js2coffee 2.2.0
