(($) ->
  $(document).ready ->

    # Function to change the page url
    ChangeUrl = (page, url) ->
      if typeof history.pushState != 'undefined'
        obj =
          Page: page
          Url: url
        history.pushState obj, obj.Page, obj.Url
      else
        alert 'Browser does not support HTML5.'
      return

    # Calendar Controls
    $('.calendar').on 'click', 'a.calendar-control', (event) ->
      href = $(this).attr('href')
      $.get href, (data) ->
        $calendar = $('table.calendar', data)
        $('table.calendar').html $calendar
        return
      ChangeUrl document.title, href
      event.preventDefault()
      false

    # Calendar Modal
    $('.calendar').on 'click', '.display-calendar-details', (event) ->
      $('.display-calendar-details').removeClass('active');
      $(this).addClass('active');
      title = $(this).attr('title');
      content = $(this).parent().next('.calendar-day-details').html();
      
      $details = $('.calendar-details .calendar-day-details');
      $details.hide();
      $details.html(content);
      $details.fadeIn(300);
      
      event.preventDefault()
      false

    return
  return
) jQuery

# ---
# generated by js2coffee 2.2.0
